### ISSUE TITLE
docker instance keep restarting

### ISSUE THREAD

**Issue by thekwonster** [wangsrGit119/janus-webrtc-gateway-docker#2]
Hello,

I'm trying to run the janus docker on ubuntu 22.04 desktop OS. (Docker version 24.02)
However, the Janus docker instance keep restarting without success. (Please check the attached jpg file)
For the Janus conf file, i only updated the general.port of the janus.transport.http.jcfg to 8086. 

Can you give me a hint to solve this problem?

Thank you!

[conf.zip](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/files/12484270/conf.zip)
![docker keep restarting](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/assets/46662703/38458a54-97c2-4f9f-9ced-210fc41da97f)
[docker-compose.zip](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/files/12492038/docker-compose.zip)

**Comment by wangsrGit119** [comment]
### 1.check your `janus.jcfg` file line 7~11,replace dirs:
```
configs_folder = "@confdir@"			# Configuration files folder
	plugins_folder = "@plugindir@"			# Plugins folder
	transports_folder = "@transportdir@"	# Transports folder
	events_folder = "@eventdir@"			# Event handlers folder
	loggers_folder = "@loggerdir@"			# External loggers folder
```
--------------
```
configs_folder = "/usr/local/etc/janus"                        
plugins_folder = "/usr/local/lib/janus/plugins"                   
transports_folder = "/usr/local/lib/janus/transports"     
events_folder = "/usr/local/lib/janus/events"                    
loggers_folder = "/tmp/loggers"
	
```
### 2. Don't use port 8086,   the nginx of container inner use it, you can use another port .

**Comment by thekwonster** [comment]
Now it works!!
Thank you so much!
