### ISSUE TITLE
Enable audiobridge plugin

### ISSUE THREAD

**Issue by EmadHelmi** [wangsrGit119/janus-webrtc-gateway-docker#3]
Hi. First of all, thank you for preparing this helpful Dockerfile.
I want to enable the `audiobridge` plugin but I don't know how.
In the `compose` file I just put this line
`./configs/janus/used/janus.plugin.audiobridge.jcfg:/usr/local/etc/janus/janus.plugin.audiobridge.jcfg`
but nothing happens and when I exec in the container and check the plugin directory there's no audiobridge plugin shared object(`so`) file. But by default, for example, the videoroom plugin `.so` file is present.

**Comment by wangsrGit119** [comment]
I build new image version ,you can try `1.2.0-slim`
```
docker pull sucwangsr/janus-webrtc-gateway-docker:1.2.0-slim
```
![20230924161619](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/assets/32221726/14c33be4-76d5-4307-bd87-5ac8685c01e2)

**Comment by EmadHelmi** [comment]
Thank you, man! You saved my time. Does it contain all the plugins?
And is your Dockerfile public? If yes, I want to have it to build any other plugins for my janus image.

**Comment by wangsrGit119** [comment]
- Media plugins is all (no lua and Duktape Interpreter,but contain has it environments):

![image](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/assets/32221726/f6b1bb91-6e37-494e-a0f9-7b06158f058c)

- Dockerfile is pubic ,in this repo, you can find .
