### ISSUE TITLE
docker instance keep restarting

### ISSUE THREAD

**Issue by DanyloIvashev** [wangsrGit119/janus-webrtc-gateway-docker#5]
Trying to run docker container on windows. I'm aware of this issue: https://github.com/wangsrGit119/janus-webrtc-gateway-docker/issues/2. What am I doing wrong? Is it possible to run this on windows?
![image](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/assets/161558307/926cbc15-da31-41b7-b92f-0d7b25243b19)
[conf.zip](https://github.com/user-attachments/files/15808061/conf.zip)
[docker-compose.zip](https://github.com/user-attachments/files/15808062/docker-compose.zip)

**Comment by wangsrGit119** [comment]
update your `janus.conf` file,the plugins folder is `/usr/local/lib/janus/plugins`
