### ISSUE TITLE
Wrong nginx root directory

### ISSUE THREAD

**Issue by ares1977** [wangsrGit119/janus-webrtc-gateway-docker#6]
Root directory was changed on commit #4  to _/usr/local/share/janus/html/demos/_ and this causes some resources used by the pages to be unavailable  (e.g., css folder located on _/usr/local/share/janus/html/_). Setting the root dir to _/usr/local/share/janus/html/_ fixes this issue.

**Comment by wangsrGit119** [comment]
Ok, have updated it, I will rebuild 1.2.3

**Comment by wangsrGit119** [comment]
![20240628094653](https://github.com/wangsrGit119/janus-webrtc-gateway-docker/assets/32221726/e2a064ba-28d2-47c8-a5a3-b537a7b377e6)

**Comment by ares1977** [comment]
Everything working as expected. Thanks!
